### PR TITLE
Fix broken chrome version.

### PR DESCRIPTION
**Pull request by iandoesallthethings**
Got this working in chrome and Arc thanks to @wheezard in #63

### CODE REVIEW

**Comment by bershanskiy** [comment]
@iandoesallthethings Hi, did you include `package-lock.json` on purpose or accidentally? Since the it was not part of the repo, it's possible that the original author did not include it intentionally.

**Comment by iandoesallthethings** [comment]
Ah, that was unintentional. Fixed it.

**Comment by bershanskiy** [comment]
@iandoesallthethings I just tested on Firefox and this PR breaks extension on Firefox since Firefox resolves paths relative to the extension page. A proper fix would be to wrap that line in `#if`/`#else`/`#endif` and process the whole file with `rollup-plugin-jscc` like other files in the project.

**Comment by bershanskiy** [comment]
Also, #70 fixes the same bug but a bit differently.

**Comment by bershanskiy** [comment]
Relevant Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1364293

**Comment by bershanskiy** [comment]
The Chromium DevTools bug (linked above) was fixed and fix was already rolled into Chromium. I tested on Chromium Version 108.0.5358.0 (Developer Build) (64-bit) and `sender.url` was fine. Most likely, Chromium Canary was already fixed too. We can expect Chromium 108 to release with Svelte DevTools working again.

**Pull request closed without merging**
